### ISSUE TITLE
missing `phraser.pkl` and naming issues

### ISSUE THREAD

**Issue by kjappelbaum** [peizong/alloy2vec#1]
Hi 👋🏽 

Thanks for the nice work. 

I was trying to get some embeddings based on your models, but ran into some issues. Some of them I can fix myself (happy to make a PR), but other's I can't. 

1. There are syntax issues in `setup.py`. Missing `:` and `"`
2. The model `pkl` file assumes that the module is called `mat2vec` (I could fix this my renaming everything `mat2vec` but would be nicer if you provide an updated `pkl`) 
3. The model wants to load a `phraser.pkl` file that I do not know where to obtain.

I'd very much appreciate if you could provide some help, particularly with the last issue. 

Cheers, 
Kevin

**Comment by kjappelbaum** [comment]
Additionally, you will need some kind of code-update or version pins as there is `np.load` that is executed for the `phraser.pkl` and new versions of numpy default to `allow_pickle=False`, which make this code fail. 

Perhaps the easiest "fix" for now would be if you provide an export of the conda environment that you used.

**Comment by peizong** [comment]
> 

Hi Kevin,

Thanks for your interest. We'll update and resolve the potential issues. My colleague and I tested it and confirmed it worked before we posted the code. However, after some code cleaning and the different versions of codes that we used to train and validate, I realize some issues may exist. To make user's life easier, I will prepare a container using singularity; users then do not need to worry about the installation.

Best,
Zongrui

**Comment by kjappelbaum** [comment]
Thanks, Zongrui! 

I think the most relevant thing would be the `phraser.pkl` file (I guess you rebuilt the phrase and didn't use the same as `mat2vec`). For the others, I can also help you if you want. 

Cheers, 
Kevin

**Comment by peizong** [comment]
> 

Hi Kevin,

Please check if you can download the pkl file here [https://www.dropbox.com/s/8173bk2zpw0fyt3/model_121520_phraser.pkl?dl=0]. It is a pretty large file that was not uploaded successfully due to GitHub policy. Later I will update the readme file and create a permanent link to the file for other users.
Put the pkl file together with other files in the models folder.

Best,
Zongrui
