### ISSUE TITLE
invalid load key

### ISSUE THREAD

**Issue by kunlu-ou** [peizong/alloy2vec#2]
Thanks for sharing your work. I am interested in playing around this model. I followed your instruction to clone the project and set up the conda environment. I also check the previous issues to download the phraser.pkl file 
Everything works fine until the example:
`from gensim.models import Word2Vec
w2v_model = Word2Vec.load("alloy2vec/training/models/model_121520")
print(w2v_model.wv.most_similar("CoCrFeMnNi"))`

When I ran this, I got an error:
  File "/home/kun/PycharmProjects/alloy2vec/example.py", line 6, in <module>
    w2v_model = Word2Vec.load("alloy2vec/training/models/model_121520")
  File "/home/kun/anaconda3/envs/alloy2vec/lib/python3.8/site-packages/gensim/models/word2vec.py", line 1141, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/home/kun/anaconda3/envs/alloy2vec/lib/python3.8/site-packages/gensim/models/base_any2vec.py", line 1230, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "/home/kun/anaconda3/envs/alloy2vec/lib/python3.8/site-packages/gensim/models/base_any2vec.py", line 602, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "/home/kun/anaconda3/envs/alloy2vec/lib/python3.8/site-packages/gensim/utils.py", line 435, in load
    obj = unpickle(fname)
  File "/home/kun/anaconda3/envs/alloy2vec/lib/python3.8/site-packages/gensim/utils.py", line 1398, in unpickle
    return _pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: invalid load key, '<'.

Any idea why this happens? Thanks in advance for your assistance.

**Comment by peizong** [comment]
Hello Kun,

I did not see this error before, unfortunately. Did you follow the steps strictly and install the correct versions of the Python libraries? Better create a conda environment specially for the installation with the suitable versions of Python.

Best,
Zongrui

**Comment by kunlu-ou** [comment]
Thanks for your response. Yes, I believe I have followed the steps in 
1. Clone the project
2. Create conda environment with Python 3.8
3. Activate the conda environment install the requirements.txt using `pip install --ignore-installed -r requirements.txt`
4. Use `python setup.py install` to download the models. I removed the `import wget` line from the setup.py as it was not used.
5. download chemdataextractor cde data download
6. Download phraser.pkl from https://www.dropbox.com/s/8173bk2zpw0fyt3/model_121520_phraser.pkl?dl=0

I did notice the model file was deleted from the dropbox link https://www.dropbox.com/s/tzl2zxzigbk2o9i/model_121520
Could that be the issue? Do you have the model file elsewhere?

**Comment by kunlu-ou** [comment]
UPDATE:

I ran the download_dash.sh to re-download the model files (it also includes the phraser.pkl file). Everything works now. I suspect the setup.py download somehow does not work as expected. It may need some update.
Thanks for your assistance.

**Comment by peizong** [comment]
Glad that you figure it out. Enjoy playing the model!

> UPDATE:
> 
> I ran the download_dash.sh to re-download the model files (it also includes the phraser.pkl file). Everything works now. I suspect the setup.py download somehow does not work as expected. It may need some update. Thanks for your assistance.
